{
 "title": "Varys Telemetry Dashboard",
 "time": { "from": "2026-03-03T05:26:42.836Z", "to": "2026-03-03T05:47:52.840Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current velocity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  alt_m - lag(alt_m) OVER (ORDER BY timestamp) AS vertical_delta\r\nFROM gps_data\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Altitude v Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  alt_m\r\nFROM gps_data\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Ground Track",
   "type": "geomap",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  lat,\r\n  lon\r\nFROM gps_data\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Last Packet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  datediff('s', max(timestamp), now()) AS seconds_since_last\r\nFROM gps_data;"
    }
   ]
  },
  {
   "title": "Apogee",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  max(alt_m) AS apogee\r\nFROM gps_data;"
    }
   ]
  },
  {
   "title": "Climb rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 6 },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  date_trunc('second', timestamp) AS \"time\",\r\n  max(alt_m) - min(alt_m) AS altitude_delta\r\nFROM gps_data\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "GPS Satellite Lock",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  sats\r\nFROM gps_data\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Current Altitude",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qdb",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  alt_m\r\nFROM gps_data\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}